### ISSUE TITLE
add function like print but returns string

### ISSUE THREAD

**Issue by crotwell** [EarthScope/mseedlib#4]
While
```
record.print(details=2)
```
is nice, it would be better if instead of print to stdout, the string could be returned. So maybe:
```
s = record.details(level=2)
```
So user can choose what to do with the string.

Also would be nice if the details/level was meaningful instead of just numbers. Assuming there are only a few level, so perhaps separate function for each, 
```
short_summary()
summary()
details()
```

**Comment by rcasey-earthscope** [comment]
An alternative to consider is to make use of macros.  e.g.

	#define RECORD_SHORT_SUMMARY 1
	#define RECORD_SUMMARY 2
	#define RECORD_DETAILS 3

**Comment by chad-earthscope** [comment]
The current `repr()` returns a string and includes a high-level summary, e.g. :

`FDSN:IU_COLA_00_L_H_1, 4, 478, 135 samples, 1.0 Hz, 2010-02-27T06:50:00.069539Z`

I think that increasing levels detail in a multi-line string become less useful to less users because each one might want different details or, more likely, formatting.  The thing is that it's easy to make such strings yourself, however you want, for example:

```Python
recstr = (f'SourceID:      {msr.sourceid}\n'
          f'PubVersion:    {msr.pubversion}\n'
          f'Record Length: {msr.reclen}\n'
          f'Num Samples:   {msr.samplecnt} samples\n'
          f'Sample Rate:   {msr.samprate} Hz\n'
          f'Start Time:    {msr.starttime_str()}')
```

So I'm hesitant to create functionality to create these complex strings at multiple levels.

What may be useful is expand the `repr()` string to something comprehensive (as it's supposed to be) and make the `str()` string the terse summary currently produced.  This would provide two levels of detail in standard interfaces.  Thoughts?

**Comment by crotwell** [comment]
Seems reasonable. Mostly I feel the function of creating a string representation should not tied only to print. And repr() and str() feel like the natural python way to handle that.
